sources:
  naija:
    - "https://audiomack.com/burna-boy/song/last-last"
    - "https://audiomack.com/wizkid/song/essence"
    - "https://audiomack.com/asake/song/yoga"
    - "https://audiomack.com/rema/song/calm-down"
  